"""Initial recovery tables

Revision ID: 958a7ab4c84e
Revises: 
Create Date: 2025-09-07 01:40:15.444661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958a7ab4c84e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('error_category', sa.String(length=100), nullable=False),
    sa.Column('error_subcategory', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('recovery_strategy', sa.String(length=100), nullable=True),
    sa.Column('can_recover', sa.Boolean(), nullable=False),
    sa.Column('system_info', sa.Text(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_error_category'), 'error_logs', ['error_category'], unique=False)
    op.create_index(op.f('ix_error_logs_logged_at'), 'error_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_error_logs_operation_id'), 'error_logs', ['operation_id'], unique=False)
    op.create_index(op.f('ix_error_logs_severity'), 'error_logs', ['severity'], unique=False)
    op.create_table('recovery_state',
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('args', sa.Text(), nullable=False),
    sa.Column('kwargs', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('recovery_metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_index(op.f('ix_recovery_state_created_at'), 'recovery_state', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_state_function_name'), 'recovery_state', ['function_name'], unique=False)
    op.create_index(op.f('ix_recovery_state_state'), 'recovery_state', ['state'], unique=False)
    op.create_index(op.f('ix_recovery_state_updated_at'), 'recovery_state', ['updated_at'], unique=False)
    op.create_table('retry_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('delay_seconds', sa.Float(), nullable=True),
    sa.Column('context', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retry_attempts_operation_id'), 'retry_attempts', ['operation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retry_attempts_operation_id'), table_name='retry_attempts')
    op.drop_table('retry_attempts')
    op.drop_index(op.f('ix_recovery_state_updated_at'), table_name='recovery_state')
    op.drop_index(op.f('ix_recovery_state_state'), table_name='recovery_state')
    op.drop_index(op.f('ix_recovery_state_function_name'), table_name='recovery_state')
    op.drop_index(op.f('ix_recovery_state_created_at'), table_name='recovery_state')
    op.drop_table('recovery_state')
    op.drop_index(op.f('ix_error_logs_severity'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_operation_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_logged_at'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_error_category'), table_name='error_logs')
    op.drop_table('error_logs')
    # ### end Alembic commands ###
